### ISSUE TITLE
Add Vote Button on Idea Workshopping page

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#1268]
### Considerations:
This ticket is focused on developing the **back end** to allow Amelia Harris to click on a "Vote" for an idea button on the [workshopping page](https://devlaunchers.org/ideaspace/workshop/25), which will then update the database to reflect her action.

This feature will allow her to show her support for an idea that she finds interesting or valuable. 

Please refer to UX designs for IdeaSpace's workshopping page in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=5fHSxtzyVh1IzGWL-1) 

### IMPORTANT ⚠️:
A similar component was developed in item #748 for liking comments that we might be able to reuse.

### Acceptance criteria:
- Clicking the "Vote" button should update the database to reflect Amelia's action.
- Amelia should only be able to vote an idea once.
- She can vote an idea by clicking on the button. If she changes his mind or voted it by mistake she should be able to click on it again and remove her vote. (Please check designs with Noa's ticket #1586)
- The number of votes for each idea should be visible to all IdeaSpace’s visitors.
- The back end should be able to handle a large number of votes without slowing down the system.

----------------------------------------------------

**Sub-tasks:**
- [X] Design
- [ ] Design Enhancement for the "vote", "Follow" and "Save" in the workshopping page (ticket #1586)
- [X] Front End Development (old for "like" button in Ideas page)
- [ ] Back end Development
- [ ] Enhancement Front-End Development (Ticket #663)
- [ ] QA

----------------------------------------------------
👇 Initial design. Please note this is a work in progress. Check with Noa's ticket #1586 for the final Hi-fi Mockups) ![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/74c05e91-fca1-48e3-8dd2-d790dd2e80aa)

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19d31d7c09559b3f9e7ac6a79c0d7b305cb2d253/image.png" alt="image.png" />

**Comment by JulieMass** [comment]
Hi @jordanmcousins ,

As you proposed yesterday I’ve created this new ticket for the development of the backend of liking an idea from the ideas page.  Please let me know if the description and acceptance criteria are OK or if I missed anything.

Thank you!

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/1268?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @MariliaDP @RETprojects

**Comment by JulieMass** [comment]
Hi @jordanmcousins ,

I’ve created the backend ticket #1268 and wanted to check with you if there are any updates needed on the acceptance criteria of this corresponding front-end ticket. Please let me know if there are any changes required and I will make sure to add them.

Thank you!

**Comment by JulieMass** [comment]
Hey @jordanmcousins, just wanted to let you know that I've updated the information in this ticket. So, this ticket will only cover the **Back-end for the vote button in the workshopping page**. We'll handle the front-end on a separate ticket. Also, I've added Noa's ticket for the enhancement of this design task. 

If you have any questions or if I missed anything, please let me know. 

(CC. @dbradham )

**Comment by JulieMass** [comment]
Update: Since Jordan needed some time off from Dev Launchers, we're gonna put this task on hold and add it back into our product backlog column to tackle it later.
