### ISSUE TITLE
Prepare Dev Launchers Developer Persona 

### ISSUE THREAD

**Issue by Nouri-Anouar** [dev-launchers/dev-launchers-platform#1295]
**Description**: In order to increase awareness of our internal team members we want to develop a detailed and accurate user persona that represents our internal Dev Launchers UX Developers.

**Tasks:**
- [ ] Define research objectives and goals for creating the user persona.
- [ ] Create an interview and/or survey guide with relevant questions to gather necessary insights.
- [ ] Set up a schedule and coordinate with potential interviewees for user interviews.
- [ ] Determine the sample size and other parameters for qualitative research methods.

**Comment by Nouri-Anouar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Universal-Design-Team-64065dde28ac6e00109e2e21/issues/dev-launchers/dev-launchers-platform/1295?planning-poker) with Zenhub @annaisaacks @Leah0996 @linakim602 @Nouri-Anouar
