### ISSUE TITLE
[US - FE DEV] As AMELIA HARRIS, I want to vote and idea from the workshopping page because I want people to know I support it.

### ISSUE THREAD

**Issue by han1ya** [dev-launchers/dev-launchers-platform#663]
### **Considerations:**
Ability to Vote an idea on the [workshopping](https://devlaunchers.org/ideaspace/workshop/25) page.  This feature will allow her to show her support for an idea that she finds interesting or valuable.

Please refer to UX designs in [Figma ](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

### **Acceptance criteria:**
- New visual design is implemented for the Vote button in the Idea [workshopping](https://devlaunchers.org/ideaspace/workshop/25) page.
- When AMELIA does a mouse over the button shows a tooltip that says "I voted this idea" appears or similar. Please check final designs on ticket #1586. 
- If no-one voted the idea yet, the button shouldn't show a counter yet. 
- If at least 1 person voted the idea, the button should show the icon + the counter showing "1".
- AMELIA can vote an idea by clicking on its button in the workshopping page. If she changes her mind or voted the idea by mistake she should be able to click on it again and remove her vote.
- After AMELIA clicks in the vote button the system should give her feedback of this action by showing a filled icon and a counter with the total of votes made.
- Amelia's total number of votes should be tracked in the dashboard as a stat of "Total votes" (please check screenshot below)
- The vote button is web responsive and it adapts for mobile, tablets and desktop breakpoints.

----------------------------------------------------
### **Sub-tasks:**
- [X] UX design
- [ ] Design Enhancement for the "vote" in the workshopping page (ticket #1586)
- [ ] Back-end Development (ticket #1268)
- [ ] Front-end Development
- [ ] QA
----------------------------------------------------

**👇 Initial designs:**

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3RoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe97132f324a3583409990997c5a0239d740124e/image.png" alt="image.png" />

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/ed23a2c5-1fb7-4106-8803-723699fa059a)

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/663?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @liwenlin664477 @Nouri-Anouar @pyxld-kris @RETprojects

**Comment by JulieMass** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/663?planning-poker) with Zenhub @alicefate

**Comment by JulieMass** [comment]
You are right! Thank you so much @RETprojects

**Comment by JulieMass** [comment]
After today's sprint review, we have decided to move this ticket to the icebox so that Remi can continue working on it once he’s done with his current tasks.

**Comment by chadcrotchett** [comment]
Moving to https://github.com/dev-launchers/dev-launchers-platform/issues/1268
