### ISSUE TITLE
[US - DEV] As AMELIA HARRIS, I want to follow an idea from the workshopping page so that I can easily get back to it from my saved list.

### ISSUE THREAD

**Issue by JulieMass** [dev-launchers/dev-launchers-platform#913]
### Considerations:
Ability to follow an idea from the [workshopping page](https://devlaunchers.org/ideaspace/browse).  This task is limited to backend development only, while the frontend will be addressed in a separate ticket.

Please refer to the Workshopping page UX designs in [Figma](https://www.figma.com/file/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=2645%3A5947&t=8soOirvjw3YvrVlo-1) 

### IMPORTANT ⚠️:
We think #688 is a related ticket from the Product Enablement team (please verify with @Enjoy2Live) 

### Acceptance criteria:
-  Remove our (old) "Save" button from all our Ideas cards in the [Ideas page](https://devlaunchers.org/ideaspace/browse) and the [IdeaSpace's dashboard](https://devlaunchers.org/ideaspace/dashboard), and continue working on the backend for the 'Ideas I Follow' as the logic will be the same.

----------------------------------------------------
### **Sub-tasks:**
- [X] UX design
- [ ] Design Enhancement for the "vote", "Follow" and "Save" in the workshopping page (ticket #1586)
- [ ] Back-end Development
- [ ] Front-end Development 
- [ ] QA

----------------------------------------------------
<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2hpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1563d5bcd5d11f00c4232bd0f0f12d35077f41d2/image.png" alt="image.png" />

"Ideas I follow" list in the dashboard page:
<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aaaea06ca3db2cddbd93c37f63bc1c661f1b6b9/image.png" alt="image.png" />

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/913?planning-poker) with Zenhub @alicefate @dbradham @jordanmcousins @JulieMass @katehirschman @Nouri-Anouar @rashikashaw @RETprojects

**Comment by dbradham** [comment]
My estimate assumes no backend work-that should be handled in #776 or a separate task.

**Comment by JulieMass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IdeaSpace-Team-6350185d9843157427cc900b/issues/dev-launchers/dev-launchers-platform/913?planning-poker) with Zenhub @jordanmcousins @rashikashaw

**Comment by JulieMass** [comment]
Hi @Rutuja177 , as we discussed today, I have updated the acceptance criteria for this ticket to include the user flow for unsaving an idea. Please let me know if this is OK or if there is anything else that I may have missed. Thank you again for bringing this to our attention today!


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBai9PIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41de9aedf2ee715c3f0fb89643dc598df2bd600b/image.png)

**Comment by Rutuja177** [comment]
Hi @JulieMass. Thank you for the update. this looks perfect.

**Comment by JulieMass** [comment]
Hey @Rutuja177 , just wanted to give you a heads up that I've made some changes to this ticket. I'll share a video on our Discord to explain in more detail, but basically, after discussing with the team following Marilia's activity, we've decided to remove the "like," "save," and "share" buttons from the ideas cards on the ideas page. We'll keep these buttons on the workshopping page. 

Also, the like button will be called "Vote" and the "Save" will be called "Follow" instead.
So, for your ticket, this means that even though the functionality will be the same, we need to remove the button on the ideas page, and you'll need to work with the "follow" button on the workshopping page. Noa is currently working on the final designs and will share them with you soon.

I also had a question for you. If you haven't started on the front-end of the "follow" button, we could focus this ticket on the "backend" to give Noa time to advance her designs. Then we can create a different ticket for the front-end of the "follow" button on the workshopping page.

I hope this all makes sense, but if you have any questions, please let me know. Thanks for your patience with this change!

(CC. @dbradham )

**Comment by Rutuja177** [comment]
Hi Julie,

Thanks for keeping me in the loop on the updates.

Finalized designs will provide a clearer roadmap for implementing the 'Ideas I Follow' flow.

In the meantime, I'll proceed with removing the "Save" button updates from the Ideas dashboard and continue working on the backend for the 'Ideas I Follow' as the logic will be the same. 

Regarding the backend changes made for #913:

In Strapi, I've created the 'Save' collection to store ideas. We can use the same collection to save the followed ideas for the user.

@dbradham

**Comment by JulieMass** [comment]
> Hi Julie,
> 
> Thanks for keeping me in the loop on the updates.
> 
> Finalized designs will provide a clearer roadmap for implementing the 'Ideas I Follow' flow.
> 
> In the meantime, I'll proceed with removing the "Save" button updates from the Ideas dashboard and continue working on the backend for the 'Ideas I Follow' as the logic will be the same.
> 
> Regarding the backend changes made for #913:
> 
> In Strapi, I've created the 'Save' collection to store ideas. We can use the same collection to save the followed ideas for the user.
> 
> @dbradham

Hey Rutuja, that's awesome! Thanks a lot for being so flexible with the recent updates 🙏.

I've updated the ticket acceptance criteria based on your feedback. Here's what I've added:

- I included the change you mentioned about removing the old “Save” button and focusing only on the Back-end for this ticket.

![image](https://github.com/dev-launchers/dev-launchers-platform/assets/104226366/bf7933eb-1a15-4445-b8cf-afbd452e3213)

**Could you please review the acceptance criteria and let me know if it looks good?** If there's anything that should be removed because this ticket only involves back-end work, just let me know.

**Comment by Rutuja177** [comment]
Thanks, Julie for the update, this looks perfect ✨

**Comment by Rutuja177** [comment]
Removed our (old) "Save" button from all our Ideas cards on the Ideas page and the IdeaSpace's dashboard, and continue working on the backend for the 'Ideas I Follow' as the logic will be the same.

**Comment by dbradham** [comment]
@JulieMass the save button no longer appears in our staging environment. Pending release, I think we can move this to closed. We may want to consider a similar ticket to remove the "like" button from the ideas until the designs are finished for "votes".

<img width="1255" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9af1a85fd29f75a88e325081c5a094b48b14ce3/image.png" alt="image.png" />

**Comment by JulieMass** [comment]
> * on from all our Ideas

Alright, thanks! Once I can see the changes in production, I'll go ahead and close the ticket. But I'm not sure when to know that new features are being moved to production. 

It would be really helpful if I could get some kind of notification when things are being moved to production. That way, I'd know to check the functionality and make sure everything is working properly, so I can then close the ticket. 

Do you know or get a notification when things are being moved to production? if so, maybe you could give me a heads up to check it? 

Let me know if there's a way we can set that up.
